# Generated by Django 2.1.2 on 2018-11-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cc_type',
            field=models.IntegerField(choices=[(1, 'Mastercard'), (2, 'VISA'), (3, 'American Express')], default=2),
        ),
    ]
