# Generated by Django 2.1.2 on 2018-11-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0003_auto_20181109_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteriaorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
