# Generated by Django 2.1.2 on 2018-11-15 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0004_cafeteriaorder_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_key',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
