# Generated by Django 2.1.2 on 2018-11-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0005_auto_20181115_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteriaorder',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
